blueprint:
  name: Tesla Smart Charge Blueprint v4
  description: >
    Example configuration:
      - smoothed_power_sensor: sensor.smoothed_power_consumed
      - charging_amps_number: number.tesla_ble_1fc6ac_charging_amps
      - charge_flap_sensor: binary_sensor.tesla_ble_1fc6ac_charge_flap
      - ble_signal_sensor: sensor.tesla_ble_1fc6ac_ble_signal
      - high_threshold: 800 W
      - low_threshold: 50 W
      - very_high_threshold: 4000 W
      - polling_minutes: 1 minute
      - random_delay_max: 30 seconds
      - divisor: 690
    This blueprint adjusts Tesla charging amperage based on power consumption using improved trigger identification.
  domain: automation
  input:
    smoothed_power_sensor:
      name: Smoothed Power Sensor
      description: Sensor measuring the smoothed power consumption.
      selector:
        entity:
          domain: sensor
      default: sensor.smoothed_power_consumed
    charging_amps_number:
      name: Charging Amps Number
      description: Number entity controlling Tesla charging amperage.
      selector:
        entity:
          domain: number
      default: number.tesla_ble_1fc6ac_charging_amps
    charge_flap_sensor:
      name: Charge Flap Sensor
      description: Binary sensor indicating if the Tesla charge flap is active.
      selector:
        entity:
          domain: binary_sensor
      default: binary_sensor.tesla_ble_1fc6ac_charge_flap
    ble_signal_sensor:
      name: BLE Signal Sensor
      description: Sensor measuring the Tesla BLE signal strength.
      selector:
        entity:
          domain: sensor
      default: sensor.tesla_ble_1fc6ac_ble_signal
    high_threshold:
      name: High Power Threshold
      description: Power value (W) above which the upper trigger is activated.
      default: 800
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: W
    low_threshold:
      name: Low Power Threshold
      description: Power value (W) below which the low trigger is activated.
      default: 50
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: W
    very_high_threshold:
      name: Very High Power Threshold
      description: Power consumption (W) above which charging is immediately disabled.
      default: 4000
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: W
    polling_minutes:
      name: Polling Interval (Minutes)
      description: Interval in minutes for the polling trigger.
      default: 1
      selector:
        number:
          min: 1
          max: 60
    random_delay_max:
      name: Random Delay Maximum (Seconds)
      description: Maximum seconds for a random delay on the polling trigger.
      default: 30
      selector:
        number:
          min: 1
          max: 120
    divisor:
      name: Divisor for Amps Adjustment
      description: Divisor used to calculate the adjustment step.
      default: 690
      selector:
        number:
          min: 1
          max: 10000

trigger:
  - platform: numeric_state
    entity_id: !input smoothed_power_sensor
    above: !input high_threshold
    for: "00:00:10"
    id: power_upper_trigger
  - platform: time_pattern
    minutes: "/{{ polling_minutes }}"
    id: polling_trigger
  - platform: numeric_state
    entity_id: !input smoothed_power_sensor
    below: !input low_threshold
    for: "00:00:01"
    id: power_low_trigger

condition:
  - condition: state
    entity_id: !input charge_flap_sensor
    state: "on"
  - condition: numeric_state
    entity_id: !input ble_signal_sensor
    above: -150

action:
  - choose:
      # Polling branch: introduce a random delay.
      - conditions:
          - condition: trigger
            id: polling_trigger
        sequence:
          - delay: "00:00:{{ range(1, (random_delay_max | int)) | random }}"
      # Low power branch: increase charging amps if below 7.
      - conditions:
          - condition: trigger
            id: power_low_trigger
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input charging_amps_number
                    below: 7
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input charging_amps_number
                    data:
                      value: >
                        {{ states(input.charging_amps_number) | int + -((states(input.smoothed_power_sensor) | float / input.divisor) | round(0)) + 1 }}
            default: []
      # Upper power branch: adjust charging amps downward or disable charging.
      - conditions:
          - condition: trigger
            id: power_upper_trigger
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input smoothed_power_sensor
                    above: !input very_high_threshold
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input charging_amps_number
                    data:
                      value: "0"
                  - stop: ""
              - conditions:
                  - condition: numeric_state
                    entity_id: !input charging_amps_number
                    above: 0
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: !input charging_amps_number
                    data:
                      value: >
                        {{ [states(input.charging_amps_number) | int - ((states(input.smoothed_power_sensor) | float / input.divisor) | round(0, 'floor')), 0] | max }}
            default: []
    default: []
mode: single
