blueprint:
  name: Tesla Smart Charge Blueprint v4 with Dual Power Sensors and Charger Switch
  description: >
    Example configuration:
      - power_consumed_sensor: sensor.power_consumed
      - power_produced_sensor: sensor.power_produced
      - charging_amps_number: number.tesla_ble_1fc6ac_charging_amps
      - charge_flap_sensor: binary_sensor.tesla_ble_1fc6ac_charge_flap
      - ble_signal_sensor: sensor.tesla_ble_1fc6ac_ble_signal
      - charger_switch: switch.tesla_ble_1fc6ac_charger_switch
      - high_threshold: 800 W
      - low_threshold: 50 W
      - very_high_threshold: 4000 W
      - polling_minutes: 1 minute
      - random_delay_max: 30 seconds
      - divisor: 690
      
    The net power is calculated as:
    
      net power = power_consumed - power_produced
      
    For additional smoothing you can define a sensor using the filter platform, for example:
    
      - platform: filter
        name: "Smoothed Power"
        entity_id: sensor.power_net
        filters:
          - filter: time_simple_moving_average
            window_size: "00:00:02"
            precision: 0
            
    This blueprint adjusts Tesla charging amperage based on the calculated net power and toggles the charger switch accordingly.
  domain: automation
  input:
    power_consumed_sensor:
      name: Power Consumed Sensor
      description: Sensor measuring power consumed.
      selector:
        entity:
          domain: sensor
      default: sensor.power_consumed
    power_produced_sensor:
      name: Power Produced Sensor
      description: Sensor measuring power produced.
      selector:
        entity:
          domain: sensor
      default: sensor.power_produced
    charging_amps_number:
      name: Charging Amps Number
      description: Number entity controlling Tesla charging amperage.
      selector:
        entity:
          domain: number
      default: number.tesla_ble_1fc6ac_charging_amps
    charge_flap_sensor:
      name: Charge Flap Sensor
      description: Binary sensor indicating if the Tesla charge flap is active.
      selector:
        entity:
          domain: binary_sensor
      default: binary_sensor.tesla_ble_1fc6ac_charge_flap
    ble_signal_sensor:
      name: BLE Signal Sensor
      description: Sensor measuring the Tesla BLE signal strength.
      selector:
        entity:
          domain: sensor
      default: sensor.tesla_ble_1fc6ac_ble
